### ISSUE TITLE
Some WAFS files are still using fHH instead of fHHH

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/WAFS#11]
Jen Yang 2021-03-12 04:29:19 UTC
In both current production gfs.v15 and parallel v16, some wafs files still use fHH in the file name. Here is some example:
 
gfs.t00z.wafs_grb45f06.grib2
wafsgfs38.t00z.gribf06
wafsgfs38.t00z.gribf06.grib2
gfs.t00z.wafs_grb45f06.nouswafs.grib2
gfs.t00z.wafs_0p25_unblended.f06.grib2

Please change the file name following the naming convention to use three digit for forecast hours: fHHH.

This can be fixed in the next major upgrade.

Refs: [Bugzilla NOAA-EMC/global-workflow#1213](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1213)

**Comment by aerorahul** [comment]
Tagging @HuiyaChuang-NOAA so it can be tracked.
@HuiyaChuang-NOAA Feel free to assign this issue appropriately

**Comment by HuiyaChuang-NOAA** [comment]
> Tagging @HuiyaChuang-NOAA so it can be tracked. @HuiyaChuang-NOAA Feel free to assign this issue appropriately

Assigned the task to Yali

**Comment by YaliMao-NOAA** [comment]
We will need to coordinate with aviation community to change fHH to fHHH.

**Comment by YaliMao-NOAA** [comment]
@HuiyaChuang-NOAA Since WAFS is going to separate from GFS, also fHH has been used for WAFS community, we will keep fHH, not change to fHHH.

**Comment by WalterKolczynski-NOAA** [comment]
@YaliMao-NOAA Please note this is a requirement from NCO and part of the implementation standards. Any exception would need to be approved by them, if that hasn't been done already.

CC @arunchawla-NOAA for informational purposes

**Comment by YaliMao-NOAA** [comment]
@WalterKolczynski-NOAA Thank you for letting us know this is a standard requirement from NCO. We will communicate with NCO about it. 
cc @HuiyaChuang-NOAA

**Comment by YaliMao-NOAA** [comment]
Close this issue which will be address in issue #23
